          ?column?          
----------------------------
 \d sp
 \d s
 \d p
 \d sp
 \d s
 \d student
 \d reviewer
 \d males
 \d offering
 \d took
 \d pg_statistic
 \d pg_type
 \d course
 \d females
 \d movie
 \d rating
 \d parent_of
 \d married_to
 \d test
 \d temp13
 \d pg_authid
 \d department
 \d agent
 \d degree
 \d country
 \d student
 \d university
 \d j
 \d spj
 \d pg_user_mapping
 \d pg_attribute
 \d pg_proc
 \d pg_class
 \d pg_attrdef
 \d pg_constraint
 \d pg_inherits
 \d pg_index
 \d pg_operator
 \d pg_opfamily
 \d pg_opclass
 \d pg_am
 \d pg_amop
 \d pg_amproc
 \d pg_language
 \d pg_largeobject_metadata
 \d pg_aggregate
 \d pg_rewrite
 \d pg_largeobject
 \d s
 \d p
 \d p
 \d pg_trigger
 \d pg_event_trigger
 \d pg_description
 \d pg_cast
 \d pg_enum
 \d pg_namespace
 \d pg_conversion
 \d pg_depend
 \d pg_database
 \d pg_db_role_setting
 \d pg_tablespace
 \d pg_pltemplate
 \d pg_auth_members
 \d pg_shdepend
 \d pg_shdescription
 \d pg_ts_config
 \d pg_ts_config_map
 \d pg_ts_dict
 \d pg_ts_parser
 \d pg_ts_template
 \d pg_extension
 \d pg_foreign_data_wrapper
 \d pg_foreign_server
 \d pg_foreign_table
 \d pg_policy
 \d pg_replication_origin
 \d pg_default_acl
 \d pg_init_privs
 \d pg_seclabel
 \d pg_shseclabel
 \d pg_collation
 \d pg_range
 \d pg_transform
 \d sql_features
 \d sql_implementation_info
 \d sql_languages
 \d sql_packages
 \d sql_parts
 \d sql_sizing
 \d sql_sizing_profiles
 \d j
 \d spj
(93 rows)

