CREATE TABLE S (
	 SNO	VARCHAR(3)	CONSTRAINT pk_S PRIMARY KEY 
	,SNAME VARCHAR(10)
	,STATUS INTEGER
	,CITY VARCHAR(10)
);

CREATE TABLE P (
	 PNO	VARCHAR(3)	CONSTRAINT pk_P PRIMARY KEY 
	,PNAME VARCHAR(10)
	,COLOR VARCHAR(5)
	,WEIGHT NUMERIC(5,2)
	,CITY VARCHAR(10)
);

CREATE TABLE SP (
	 SNO	VARCHAR(3)	 
	,PNO	VARCHAR(3)	 
	,QTY  INTEGER
,CONSTRAINT pk_SP PRIMARY KEY(SNO,PNO)
);




