--  INSERTING VALUES IN S

INSERT INTO S VALUES('S1','SMITH',20 ,'LONDON');

INSERT INTO S VALUES('S2','JONES',10 ,'PARIS');

INSERT INTO S VALUES('S3','BLAKE',30 ,'PARIS');

INSERT INTO S VALUES('S4','CLARK',20 ,'LONDON');

INSERT INTO S VALUES('S5','ADAMS',30 ,'ATHENS');

INSERT INTO S VALUES('S6','HENRY',12 ,'GUELPH');

--  INSERTING VALUES IN P

INSERT INTO P VALUES('P1', 'NUT', 'RED', 12.0, 'LONDON');

INSERT INTO P VALUES('P2', 'BOLT', 'GREEN', 17.0, 'PARIS');

INSERT INTO P VALUES('P3', 'SCREW', 'BLUE', 17.0, 'ROME');

INSERT INTO P VALUES('P4', 'SCREW', 'RED', 14.0, 'LONDON');

INSERT INTO P VALUES('P5', 'CAN', 'BLUE', 12.0, 'PARIS');

INSERT INTO P VALUES('P6', 'COG', 'RED', 19.0, 'LONDON');


--  INSERTING VALUES IN SP

INSERT INTO SP VALUES('S1', 'P1', 200);

INSERT INTO SP VALUES('S2', 'P3', 400);

INSERT INTO SP VALUES('S2', 'P5', 100);

INSERT INTO SP VALUES('S3', 'P3', 200);

INSERT INTO SP VALUES('S3', 'P4', 500);

INSERT INTO SP VALUES('S4', 'P6', 300);

INSERT INTO SP VALUES('S5', 'P2', 200);

INSERT INTO SP VALUES('S5', 'P5', 500);

INSERT INTO SP VALUES('S5', 'P6', 200);

INSERT INTO SP VALUES('S5', 'P1', 100);

INSERT INTO SP VALUES('S5', 'P3', 200);

INSERT INTO SP VALUES('S5', 'P4', 800);



